# =============================
# Fichier de configuration Docker Compose pour l'application ICTGROUP avec Supabase
# - web : application Django (utilise Supabase comme base de données)
# Les variables Supabase sont à placer dans un fichier .env à la racine du projet
# =============================

# Version de Docker Compose
version: '3.8'

# Définition des services de l'application
services:
  # Service de l'application web Django avec Supabase
  web:
    # Construction de l'image Docker à partir du Dockerfile dans le répertoire docker
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Commande à exécuter au démarrage du conteneur web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # Variables d'environnement chargées depuis le fichier .env
    env_file:
      - .env
    # Exposition du port 8000 du conteneur vers le port 8000 de l'hôte
    ports:
      - "8000:8000"
    # Volumes pour le développement (hot reload)
    volumes:
      - .:/code
    # Variables d'environnement spécifiques à Docker
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1

# Note: Les services PostgreSQL locaux ont été supprimés car nous utilisons Supabase
# Pour accéder à votre base Supabase, utilisez le dashboard web sur supabase.com
# URL du dashboard: https://ksjouzrbwrltuzyekvle.supabase.co
