# Generated by Django 5.2.4 on 2025-07-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extranet", "0006_leaverequest_demi_jour"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="site",
            field=models.CharField(
                choices=[("tunisie", "Tunisie"), ("france", "France")],
                default="tunisie",
                max_length=10,
            ),
        ),
    ]
