# Generated by Django 5.2.5 on 2025-08-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extranet", "0020_alter_usermonthlyreportcache_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="carry_over",
        ),
    ]
