# Generated by Django 5.2.5 on 2025-08-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extranet", "0021_performance_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="carry_over",
        ),
    ]
