# Generated by Django 5.2.5 on 2025-08-30 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_address', models.TextField(verbose_name='Adresse du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire HT')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total HT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intranet.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('supplier_address', models.TextField(verbose_name='Adresse du fournisseur')),
                ('supplier_email', models.EmailField(max_length=254, verbose_name='Email du fournisseur')),
                ('supplier_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du fournisseur')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('approved', 'Approuvé'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file_type', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('contract', 'Contrat'), ('quote', 'Devis'), ('other', 'Autre')], max_length=20, verbose_name='Type de fichier')),
                ('file', models.FileField(upload_to='intranet/attachments/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.invoice', verbose_name='Facture liée')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.purchaseorder', verbose_name='Bon de commande lié')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intranet.purchaseorder')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bon de commande',
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense'), ('transfer', 'Virement')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(choices=[('sales', 'Ventes'), ('services', 'Services'), ('supplies', 'Fournitures'), ('rent', 'Loyer'), ('utilities', 'Charges'), ('salary', 'Salaires'), ('taxes', 'Taxes'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('from_account', models.CharField(blank=True, max_length=100, verbose_name='Compte source')),
                ('to_account', models.CharField(blank=True, max_length=100, verbose_name='Compte destination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Transaction trésorerie',
                'verbose_name_plural': 'Transactions trésorerie',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
