name: Fly Deploy (disabled)

# This workflow is disabled because deployment is handled by `ci-cd.yml`.
on: [workflow_dispatch]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Fly deploy workflow disabled; use ci-cd.yml build-and-deploy job"
